version: '3.8'

services:
  # PostgreSQL - Banco principal
  postgres:
    image: postgres:15-alpine
    container_name: matriz-postgres
    environment:
      POSTGRES_DB: matriz_coleta
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - matriz-network

  # Neo4j - Banco de grafos
  neo4j:
    image: neo4j:5.15-community
    container_name: matriz-neo4j
    environment:
      NEO4J_AUTH: neo4j/admin123
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: "gds.*,apoc.*"
      NEO4J_dbms_security_procedures_allowlist: "gds.*,apoc.*"
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - matriz-network

  # Redis - Cache e filas
  redis:
    image: redis:7-alpine
    container_name: matriz-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - matriz-network
    command: redis-server --appendonly yes

  # Backend Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: matriz-backend
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: matriz_coleta
      DB_USER: admin
      DB_PASSWORD: admin123
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: admin123
      REDIS_URL: redis://redis:6379
      JWT_SECRET: matriz_coleta_jwt_secret_2024
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - postgres
      - neo4j
      - redis
    networks:
      - matriz-network
    command: npm run dev

  # Frontend React - Matriz de Coleta
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: matriz-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001
      REACT_APP_WS_URL: ws://localhost:3001
      CHOKIDAR_USEPOLLING: true
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - matriz-network
    command: npm start

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  redis_data:

networks:
  matriz-network:
    driver: bridge 